### ISSUE TITLE
Maintain the connection between the client and the server and change the value of the string sent

### ISSUE THREAD

**Issue by Blandine11** [dtikhonov/lsquic-tutorial#1]
I have two concerns  about this lsquic's tutorial (https://github.com/dtikhonov/lsquic-tutorial/blob/master/tut.c).
Concern 1 : 
You said that server reads a string from client, reverse it and sends it back to client.
I tried to see where the string is given in the code but I didn't see.
Can you show me how and where can I get the value of spec[n].iov in order to see the value of the
string sent between client and server, please? 

Concern 2 : 
How can I do to maintain the connexion between client and server and send the string many times?

Apologize me for many questions, I'm new on lsquic and also on socket programming.

Your help will be appreciated.

Regards

**Comment by Blandine11** [comment]
Hello all,

Can Someone help me, please ?

Regards

**Comment by dtikhonov** [comment]
1. The string is read from standard input by the client program.
1. The connection is maintained until the client closes it.  You can enter as many strings as you'd like: only one connection will be used.  You can turn on logging to see more information.

**Comment by Blandine11** [comment]
Ok, thanks.

Then if I want to send the srting "Hello server"  to the server,
I need to add it as parameter  when I launch the client program?
Like this ./tut .... IP port  "Hello server"

**Comment by dtikhonov** [comment]
Usage examples are provided in the README: https://github.com/dtikhonov/lsquic-tutorial

**Comment by Blandine11** [comment]
Ok,

Thank you for your help.

I'm going to close this issue.

Regards
